image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  - cp ./.well-known/acme-challenge/HbUDS8TbgvYwY3BrL87vrJbauqMtRSDYO2l01I6i7xU.html ./.well-known/acme-challenge/HbUDS8TbgvYwY3BrL87vrJbauqMtRSDYO2l01I6i7xU
  artifacts:
    paths:
    - public
  only:
  - master
