image: ruby:2.3

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  - cp ./.well-known/acme-challenge/8O3LgF26IIT-lZIdOiVaxUsm5gyGM00sJabTV2CM30U.html ./.well-known/acme-challenge/8O3LgF26IIT-lZIdOiVaxUsm5gyGM00sJabTV2CM30U
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
